### ISSUE TITLE
求更新osu format v14

### ISSUE THREAD

**Issue by fishfish030** [delguoqing/osu2tja#2]
求更新🙏，最新的osu format已经到v14了

**Comment by delguoqing** [comment]
有点困难，退坑N年了。你看看有人应该fork了仓库在修改，你先看看那个是否可以满足需求？

如果不行的话，我看看有没有哪天有空改一下。

发自我的iPhone

在 2023年4月4日，17:59，fishfish030 ***@***.***> 写道：

﻿

求更新🙏，最新的osu format已经到v14了

**Comment by fishfish030** [comment]
我试过SamLangTen的fork，但好象也不支援v14，有不少format v14歌曲会出现错误：
NameError: name 'MEASURE' is not defined
AssertionError: Need at least one timing point
还有个format v5的谱卡在<class 'str'>
若是哪天有空希望能更新，谢谢🙏

**Comment by fishfish030** [comment]
有些v13、v14的歌曲是正常的，中间偶尔有点延迟，影响不大

**Comment by delguoqing** [comment]
可否提供一些不兼容的map的id给我？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月4日 19:27
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [delguoqing/osu2tja] 求更新osu format v14 (Issue #2)


有些v13、v14的歌曲是正常的，中间偶尔有点延迟，影响不大

―

**Comment by fishfish030** [comment]
v14: 1477241 (AssertionError: Need at least one timing point)
v14: 1945047 (AssertionError: Need at least one timing point)
v14: 500464 (NameError: name 'MEASURE' is not defined)
v5: 5542 (卡在<class 'str'>)
v9: 54720 (卡在<class 'str'>)
已经在osu实测过，歌曲是正常的

**Comment by delguoqing** [comment]
我修改了一下，把一些报错都排除了，顺便升级到了Python 3.

暂时都可以用了，但也只是可以用了，转出来的效果我没有测试。
但是我没敢动里面的那些转换逻辑，有点绕，我不是很清楚当年的我为什么要这么写，但是一般来讲是有理由的。

另外v5 太老了，我不是很确定那个时候为什么没有支持，但是你现在可以通过添加-i选项来忽略版本检查，我测过可以用的。

**Comment by fishfish030** [comment]
试过几首歌，确实可以用了，感谢更新
